# Generated by Django 4.1.2 on 2023-08-28 08:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='classes',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='date_time_class',
        ),
    ]
