# Generated by Django 4.1 on 2022-09-28 18:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClassRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.IntegerField(verbose_name='شماره کلاس')),
                ('shift', models.CharField(choices=[('M', 'صبح'), ('E', 'عصر')], max_length=1, verbose_name='شیفت کلاسی')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='نام')),
                ('last_name', models.CharField(max_length=100, verbose_name='نام خانوادگی')),
                ('father_name', models.CharField(max_length=100, null=True, verbose_name='نام پدر')),
                ('id_code', models.IntegerField(unique=True, verbose_name='کد ملی')),
                ('level', models.CharField(choices=[('10', 'دهم'), ('12', 'یازدهم'), ('11', 'دوازدهم')], max_length=2, verbose_name='پایه')),
                ('level_up', models.BooleanField(default=False, verbose_name='قبول شده / قبول نشده')),
            ],
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alarm', models.CharField(blank=True, choices=[('1', 'زنگ اول'), ('2', 'زنگ دوم'), ('3', 'زنگ سوم'), ('4', 'زنگ چهارم')], max_length=1, null=True, verbose_name='زنگ')),
                ('attendance', models.CharField(choices=[('1', 'حاضر'), ('2', 'تاخیر'), ('3', 'غیبت'), ('4', 'غیبت موجه'), ('5', 'غیبت غیر موجه'), ('6', 'مرخصی')], default=1, max_length=1, verbose_name='حضور و غیاب')),
                ('time_takhir', models.CharField(blank=True, max_length=100, null=True, verbose_name='زمان تاخیر')),
                ('gheybat_movajah', models.TextField(blank=True, null=True, verbose_name='غیبت موجه')),
                ('gheybat_gheyr_movajah', models.TextField(blank=True, null=True, verbose_name='غیبت غیر موجه')),
                ('morkhasi', models.TextField(blank=True, null=True, verbose_name='مرخصی')),
                ('date_attendance', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Student.student', verbose_name='دانش آموزش')),
            ],
        ),
    ]
