# Generated by Django 4.1 on 2022-10-05 06:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Assign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('shift', models.CharField(choices=[('صبح', 'صبح'), ('عصر', 'عصر')], max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Reshte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('full_name', models.CharField(max_length=200)),
                ('father_name', models.CharField(max_length=100)),
                ('id_code', models.UUIDField(unique=True)),
                ('level', models.CharField(choices=[('دهم', 'دهم'), ('یازدهم', 'یازدهم'), ('دوازدهم', 'دوازدهم')], max_length=8)),
                ('level_up', models.BooleanField(default=False)),
                ('date', models.DateField()),
                ('usn', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('class_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Student.class')),
                ('reshte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Student.reshte')),
            ],
        ),
        migrations.AddField(
            model_name='class',
            name='reshte',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Student.reshte'),
        ),
        migrations.CreateModel(
            name='AttendanceClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('status', models.IntegerField(default=0)),
                ('assign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Student.assign')),
            ],
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('status', models.BooleanField(default=True)),
                ('gheybat_text', models.CharField(blank=True, max_length=500, null=True)),
                ('attendanceclass', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Student.attendanceclass')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Student.student')),
            ],
        ),
        migrations.AddField(
            model_name='assign',
            name='class_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Student.class'),
        ),
    ]
