# Generated by Django 4.1 on 2022-10-05 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='class',
            name='reshte',
        ),
    ]
