# Generated by Django 4.1 on 2022-10-07 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='gheybat_text',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
