# Generated by Django 4.1 on 2022-10-11 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0002_attendance_gheybat_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='zang',
            field=models.CharField(blank=True, choices=[('اول', 'اول'), ('دوم', 'دوم'), ('سوم', 'سوم')], max_length=10, null=True),
        ),
    ]
