# Generated by Django 4.1 on 2022-10-05 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0002_remove_class_reshte'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='id_code',
            field=models.IntegerField(max_length=10, unique=True),
        ),
    ]
