# Generated by Django 4.1 on 2022-09-29 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0002_student_class_room'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='attendance',
            field=models.CharField(choices=[('1', 'حاضر'), ('2', 'تاخیر'), ('3', 'غیبت موجه'), ('4', 'غیبت غیر موجه'), ('5', 'مرخصی')], default=1, max_length=1, verbose_name='حضور و غیاب'),
        ),
    ]
