# Generated by Django 4.1 on 2022-10-11 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0003_attendance_zang'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='zang',
        ),
    ]
