# Generated by Django 4.1 on 2022-10-05 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0004_level_alter_student_id_code_alter_student_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='level',
            field=models.CharField(choices=[('دهم', 'دهم'), ('یازدهم', 'یازدهم'), ('دوازدهم', 'دوازدهم')], max_length=8),
        ),
        migrations.DeleteModel(
            name='Level',
        ),
    ]
