# Generated by Django 4.1.2 on 2022-10-19 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0004_remove_attendance_zang'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='zang',
            field=models.BooleanField(blank=True, choices=[('1', '1'), ('2', '2')], null=True),
        ),
    ]
