# Generated by Django 4.1.2 on 2022-10-19 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0005_attendance_zang'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='zang',
        ),
        migrations.AddField(
            model_name='attendanceclass',
            name='zang',
            field=models.CharField(blank=True, choices=[('1', '1'), ('2', '2')], max_length=1, null=True),
        ),
    ]
