# Generated by Django 4.1.2 on 2022-10-19 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0007_alter_attendanceclass_zang'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendanceclass',
            name='zang',
        ),
        migrations.AddField(
            model_name='student',
            name='zang',
            field=models.BooleanField(blank=True, choices=[('1', '1'), ('2', '2')], null=True),
        ),
    ]
