# Generated by Django 4.1.2 on 2022-10-31 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0008_remove_attendanceclass_zang_student_zang'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='zang',
            field=models.CharField(blank=True, choices=[('اول', 'اول'), ('دوم', 'دوم'), ('دوم', 'دوم')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='zang',
            field=models.BooleanField(blank=True, choices=[('اول', 'اول'), ('دوم', 'دوم'), ('دوم', 'دوم')], null=True),
        ),
    ]
