# Generated by Django 4.1.2 on 2022-10-31 16:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0009_attendance_zang_alter_student_zang'),
    ]

    operations = [
        migrations.CreateModel(
            name='Zang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
            ],
        ),
        migrations.AlterField(
            model_name='attendance',
            name='zang',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Student.zang'),
        ),
    ]
